<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: gonglc
 * Date: Tue, 31 Oct 2017 12:12:04 +0100
 */

$conf['title'] = 'skyon';
$conf['lang'] = 'zh';
$conf['tagline'] = '---逆水行舟,不进则退';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['maxtoclevel'] = '5';
$conf['useacl'] = 1;
$conf['autopasswd'] = 0;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'profile_delete';
$conf['htmlok'] = 1;
$conf['fnencode'] = 'utf-8';
$conf['plugin']['indexmenu']['skip_file'] = '/(:sidebar$|sidebar$)/';

// end auto-generated content
